name: Game Compatibility
description: Report a game's compatibility status on PlayCover
body:
  - type: input
    id: game-name
    attributes:
      label: Game Name
      placeholder: ## Game Name
    validations:
      required: true
  - type: input
    id: game-version
    attributes:
      label: Game Update Version
      placeholder: #### *(e.g. 1.0.0 or 1.1.3)*
    validations:
      required: true
  - type: input
    id: playcover-version
    attributes:
      label: PlayCover Build Version
      placeholder: #### *(e.g. 2.0.4)*
    validations:
      required: true
  - type: input
    id: macos-version
    attributes:
      label: MacOS Version
      placeholder: #### *(e.g. 13.1, Beta 13.2(22D49))*
    validations:
      required: true
  - type: input
    id: app-id
    attributes:
      label: Bundle ID or App Store ID
      placeholder: #### *(e.g. com.mihoyo.genshin, 1517783697)*
    validations:
      required: true
  - type: textarea
    id: hardware-specs
    attributes:
      label: Hardware Specs
      value: |
        - ##### Mac model: *(e.g. Macbook Pro)*
        - ##### Chip model: *(e.g. M1, M2)*
        - ##### Display size: *(e.g. 13", 16-inch)*
    validations:
      required: true
  - type: textarea
    id: game-state
    attributes:
      label: "Game State"
      description: "Describe the current game state here."
      placeholder: /
        - Describe the current game state here. 
        - List the issues you've noticed if there are any. 
        - Add links to related issues from the main repository if they exist.
        - Add links to pull requests that fix issues described if/when applicable. 
        - Add a zipped save file for easy access to any issues if needed, namely for situations that can only be accessed after several hours of gameplay.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Add screenshots here (preferably on windowed mode) if the game is rendering.
      placeholder: Drag and drop the images/screenshots onto the text area.
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: Any log file such as crash logs. You can find them in the Console app.
      placeholder: Drag and drop the log file onto the text area.
    validations:
      required: false
